name: regular
on: [push]
env:
    SECRETE: 'secret'
jobs:
    regular:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node
              uses: actions/setup-node@v2
              with:
                  node-version: '14.x'
            - name: 'print starting'
              run: echo "START"
            - name: Install typescript
              run: npm install typescript -g
            - name: Installing dependencies
              run: npm install
            - name: build the server
              run: npm build
